apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: order-history-service-runtime
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ftgo-vault
    kind: ClusterSecretStore
  target:
    name: order-history-service-runtime
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: SPRING_CASSANDRA_USERNAME
      remoteRef:
        key: production/order-history-service
        property: scylla.username
    - secretKey: SPRING_CASSANDRA_PASSWORD
      remoteRef:
        key: production/order-history-service
        property: scylla.password
    - secretKey: SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG
      remoteRef:
        key: production/order-history-service
        property: kafka.sasl-jaas-config
    - secretKey: FTGO_ORDER_HISTORY_PAGING_SECRET
      remoteRef:
        key: production/order-history-service
        property: paging.hmac-secret
    - secretKey: FTGO_SECURITY_ISSUER_URI
      remoteRef:
        key: production/order-history-service
        property: security.issuer-uri
    - secretKey: FTGO_SECURITY_JWK_SET_URI
      remoteRef:
        key: production/order-history-service
        property: security.jwk-set-uri
