apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-history-service
spec:
  template:
    spec:
      containers:
        - name: order-history-service
          envFrom:
            - secretRef:
                name: order-history-service-runtime
