apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
spec:
  template:
    spec:
      containers:
        - name: delivery-service
          envFrom:
            - secretRef:
                name: delivery-service-runtime
