spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**
        - id: consumer-service
          uri: http://localhost:8082
          predicates:
            - Path=/consumers/**
        - id: restaurant-service
          uri: http://localhost:8083
          predicates:
            - Path=/restaurants/**
        - id: kitchen-service
          uri: http://localhost:8084
          predicates:
            - Path=/tickets/**
        - id: delivery-service
          uri: http://localhost:8086
          predicates:
            - Path=/deliveries/**
        - id: order-history-service
          uri: http://localhost:8087
          predicates:
            - Path=/order-history/**
  redis:
    host: localhost
    port: 6379

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
