apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: order-service-runtime
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ftgo-vault
    kind: ClusterSecretStore
  target:
    name: order-service-runtime
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: production/order-service
        property: database.username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: production/order-service
        property: database.password
    - secretKey: SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG
      remoteRef:
        key: production/order-service
        property: kafka.sasl-jaas-config
    - secretKey: FTGO_SECURITY_ISSUER_URI
      remoteRef:
        key: production/order-service
        property: security.issuer-uri
    - secretKey: FTGO_SECURITY_JWK_SET_URI
      remoteRef:
        key: production/order-service
        property: security.jwk-set-uri
