apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
spec:
  template:
    spec:
      containers:
        - name: restaurant-service
          envFrom:
            - secretRef:
                name: restaurant-service-runtime
