apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: restaurant-service
  ports:
    - name: http
      port: 8080
      targetPort: http
