apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: order-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: order-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: consumer-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: consumer-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: restaurant-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: restaurant-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kitchen-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kitchen-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: accounting-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: accounting-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: delivery-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: delivery-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: order-history-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: order-history-service
