apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounting-service
spec:
  template:
    spec:
      containers:
        - name: accounting-service
          envFrom:
            - secretRef:
                name: accounting-service-runtime
