apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-gateway-runtime
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ftgo-vault
    kind: ClusterSecretStore
  target:
    name: api-gateway-runtime
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: FTGO_SECURITY_ISSUER_URI
      remoteRef:
        key: production/api-gateway
        property: security.issuer-uri
    - secretKey: FTGO_SECURITY_JWK_SET_URI
      remoteRef:
        key: production/api-gateway
        property: security.jwk-set-uri
    - secretKey: SPRING_DATA_REDIS_PASSWORD
      remoteRef:
        key: production/api-gateway
        property: redis.password
