spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3311/ftgo_delivery?createDatabaseIfNotExist=true
    username: ftgo_user
    password: ftgo_password
